name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arpitjindal97
          password: ${{ secrets.GIT_PAT_TOKEN }}
      - name: Build Image
        run: docker build -t ghcr.io/arpitjindal97/stm:latest . -f Dockerfile
      - name: Push Image
        run: docker push ghcr.io/arpitjindal97/stm:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: 'http://13.235.49.243'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Deployment
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: ubuntu@13.235.49.243
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        deployment_mode: docker-compose
        copy_stack_file: true
        deploy_path: /home/ubuntu
        stack_file_name: docker-compose.yml
        keep_files: 1
        docker_prune: true
        pull_images_first: true
        args: up -d